# Generated by Django 5.1.6 on 2025-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=models.CharField(max_length=100),
        ),
    ]
