# Generated by Django 5.1.6 on 2025-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_tax"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="color",),
        migrations.RemoveField(model_name="orderproduct", name="size",),
    ]
