# Generated by Django 5.1.6 on 2025-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderproduct_color_remove_orderproduct_size"),
        ("store", "0003_alter_variation_variation_value"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="variation",),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
